//
// Autogenerated by Thrift Compiler (0.20.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
'use strict';

const thrift = require('thrift');
const Thrift = thrift.Thrift;
const Int64 = require('node-int64');

const RoomService = require('./RoomService');
const RoomServiceClient = RoomService.Client;
const RoomServiceProcessor = RoomService.Processor;
const ttypes = require('./room_types');
//HELPER FUNCTIONS AND STRUCTURES

const RoomService2_b_args = class {
    constructor(args) {
        this.b = null;
        if (args) {
            if (args.b !== undefined && args.b !== null) {
                this.b = args.b;
            }
        }
    }

    read(input) {
        input.readStructBegin();
        while (true) {
            const ret = input.readFieldBegin();
            const ftype = ret.ftype;
            const fid = ret.fid;
            if (ftype == Thrift.Type.STOP) {
                break;
            }
            switch (fid) {
                case -1:
                    if (ftype == Thrift.Type.STRING) {
                        this.b = input.readBinary();
                    } else {
                        input.skip(ftype);
                    }
                    break;
                case 0:
                    input.skip(ftype);
                    break;
                default:
                    input.skip(ftype);
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return;
    }

    write(output) {
        output.writeStructBegin('RoomService2_b_args');
        if (this.b !== null && this.b !== undefined) {
            output.writeFieldBegin('b', Thrift.Type.STRING, -1);
            output.writeBinary(this.b);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
};
const RoomService2_b_result = class {
    constructor(args) {
        this.success = null;
        if (args) {
            if (args.success !== undefined && args.success !== null) {
                this.success = args.success;
            }
        }
    }

    read(input) {
        input.readStructBegin();
        while (true) {
            const ret = input.readFieldBegin();
            const ftype = ret.ftype;
            const fid = ret.fid;
            if (ftype == Thrift.Type.STOP) {
                break;
            }
            switch (fid) {
                case 0:
                    if (ftype == Thrift.Type.STRING) {
                        this.success = input.readBinary();
                    } else {
                        input.skip(ftype);
                    }
                    break;
                case 0:
                    input.skip(ftype);
                    break;
                default:
                    input.skip(ftype);
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return;
    }

    write(output) {
        output.writeStructBegin('RoomService2_b_result');
        if (this.success !== null && this.success !== undefined) {
            output.writeFieldBegin('success', Thrift.Type.STRING, 0);
            output.writeBinary(this.success);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
};
const RoomService2Client = (exports.Client = class RoomService2Client extends RoomServiceClient {
    constructor(output, pClass) {
        super(output, pClass);
        this.output = output;
        this.pClass = pClass;
        this._seqid = 0;
        this._reqs = {};
    }
    seqid() {
        return this._seqid;
    }
    new_seqid() {
        return (this._seqid += 1);
    }

    b(b) {
        this._seqid = this.new_seqid();
        const self = this;
        return new Promise((resolve, reject) => {
            self._reqs[self.seqid()] = (error, result) => {
                return error ? reject(error) : resolve(result);
            };
            self.send_b(b);
        });
    }

    send_b(b) {
        const output = new this.pClass(this.output);
        const params = {
            b: b,
        };
        const args = new RoomService2_b_args(params);
        try {
            output.writeMessageBegin('b', Thrift.MessageType.CALL, this.seqid());
            args.write(output);
            output.writeMessageEnd();
            return this.output.flush();
        } catch (e) {
            delete this._reqs[this.seqid()];
            if (typeof output.reset === 'function') {
                output.reset();
            }
            throw e;
        }
    }

    recv_b(input, mtype, rseqid) {
        const callback = this._reqs[rseqid] || function () {};
        delete this._reqs[rseqid];
        if (mtype == Thrift.MessageType.EXCEPTION) {
            const x = new Thrift.TApplicationException();
            x.read(input);
            input.readMessageEnd();
            return callback(x);
        }
        const result = new RoomService2_b_result();
        result.read(input);
        input.readMessageEnd();

        if (null !== result.success) {
            return callback(null, result.success);
        }
        return callback('b failed: unknown result');
    }
});
const RoomService2Processor = (exports.Processor = class RoomService2Processor extends RoomServiceProcessor {
    constructor(handler) {
        super(handler);
        this._handler = handler;
    }
    process(input, output) {
        const r = input.readMessageBegin();
        if (this['process_' + r.fname]) {
            return this['process_' + r.fname].call(this, r.rseqid, input, output);
        } else {
            input.skip(Thrift.Type.STRUCT);
            input.readMessageEnd();
            const x = new Thrift.TApplicationException(
                Thrift.TApplicationExceptionType.UNKNOWN_METHOD,
                'Unknown function ' + r.fname,
            );
            output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
            x.write(output);
            output.writeMessageEnd();
            output.flush();
        }
    }
    process_b(seqid, input, output) {
        const args = new RoomService2_b_args();
        args.read(input);
        input.readMessageEnd();
        if (this._handler.b.length === 1) {
            new Promise((resolve) => resolve(this._handler.b.bind(this._handler)(args.b)))
                .then((result) => {
                    const result_obj = new RoomService2_b_result({ success: result });
                    output.writeMessageBegin('b', Thrift.MessageType.REPLY, seqid);
                    result_obj.write(output);
                    output.writeMessageEnd();
                    output.flush();
                })
                .catch((err) => {
                    let result;
                    result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
                    output.writeMessageBegin('b', Thrift.MessageType.EXCEPTION, seqid);
                    result.write(output);
                    output.writeMessageEnd();
                    output.flush();
                });
        } else {
            this._handler.b(args.b, (err, result) => {
                let result_obj;
                if (err === null || typeof err === 'undefined') {
                    result_obj = new RoomService2_b_result(
                        err !== null || typeof err === 'undefined' ? err : { success: result },
                    );
                    output.writeMessageBegin('b', Thrift.MessageType.REPLY, seqid);
                } else {
                    result_obj = new Thrift.TApplicationException(
                        Thrift.TApplicationExceptionType.UNKNOWN,
                        err.message,
                    );
                    output.writeMessageBegin('b', Thrift.MessageType.EXCEPTION, seqid);
                }
                result_obj.write(output);
                output.writeMessageEnd();
                output.flush();
            });
        }
    }
});
