//
// Autogenerated by Thrift Compiler (0.14.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import thrift = require('thrift');
import Thrift = thrift.Thrift;
import Q = thrift.Q;
import Int64 = require('node-int64');

/**
 * rtc room info
 */
declare class RoomInfo {
    public id: string;
    public expires: number;
    public username: string;
    public password: string;

    constructor(args?: { id: string; expires: number; username: string; password?: string });
}
